/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6b3900",
        "on-secondary-fixed": "#2e1500",
        "inverse-surface": "#273141",
        "on-primary-container": "#00544f",
        "primary-fixed-dim": "#5dd9d0",
        "secondary-container": "#fc9d41",
        "inverse-on-surface": "#ebf1ff",
        "outline-variant": "#bcc9c7",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#b8b2ff",
        "secondary-fixed": "#ffdcc2",
        background: "#f9f9ff",
        "inverse-primary": "#5dd9d0",
        "primary-fixed": "#7cf6ec",
        "on-tertiary": "#ffffff",
        surface: "#f9f9ff",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#d9e3f9",
        "secondary-fixed-dim": "#ffb77a",
        "on-primary-fixed": "#00201e",
        "on-error-container": "#93000a",
        "surface-dim": "#d0daf0",
        primary: "#006a65",
        "on-primary-fixed-variant": "#00504c",
        outline: "#6c7a78",
        "on-secondary-fixed-variant": "#6d3a00",
        "surface-container-high": "#dee8ff",
        "surface-container-low": "#f0f3ff",
        "on-surface-variant": "#3d4948",
        "on-surface": "#121c2c",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e3dfff",
        "on-tertiary-fixed": "#140067",
        "primary-container": "#4ecdc4",
        "tertiary-fixed-dim": "#c5c0ff",
        "on-tertiary-container": "#453d99",
        "on-tertiary-fixed-variant": "#413996",
        "surface-container-highest": "#d9e3f9",
        secondary: "#8f4e00",
        tertiary: "#5952af",
        "on-error": "#ffffff",
        "on-background": "#121c2c",
        "surface-tint": "#006a65",
        error: "#ba1a1a",
        "surface-container": "#e7eeff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Lexend", "sans-serif"],
        body: ["Lexend", "sans-serif"],
        label: ["Lexend", "sans-serif"],
        lexend: ["Lexend", "sans-serif"],
      },
    },
  },
  plugins: [],
};
